apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    io.kompose.service: app
spec:
  selector:
    app: app
  ports:
  - protocol: TCP
    port: 9002
  selector:
    io.kompose.service: app
status:
  loadBalancer: {}
