apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml --volumes hostPath convert
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yml --volumes hostPath convert
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: db
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: db73
        - name: MYSQL_ROOT_PASSWORD
          value: root8888
        image: mysql:8.0.13
        name: db
        ports:
        - containerPort: 3306
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: db-hostpath0
        - mountPath: /etc/mysql/conf.d
          name: db-hostpath1
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /usr/local/var/mysql8
        name: db-hostpath0
      - hostPath:
          path: /Users/mac/work/docker/conf/mysql
        name: db-hostpath1
status: {}
