apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  type: NodePort
  ports:
  - name: "81"
    port: 81
    targetPort: 81
  - name: "82"
    port: 82
    targetPort: 82
  selector:
    name: nginx
status:
  loadBalancer: {}
