apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: node
  name: node
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - image: shtrm/toirus-cp:v1.1
        name: node
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
