apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  labels:
    app: redis
spec:
  capacity:
    storage: 100Mi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/mac/work/docker/redis
