apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-pv
  labels:
    app: app
spec:
  capacity:
    storage: 100Mi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/mac/work/docker/toirus-app
