apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-disk
  labels:
    app: toirus
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
