apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: gray
  name: gray
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: gray
    spec:
      containers:
      - env:
        - name: GRAYLOG_HTTP_PUBLISH_URI
          value: http://127.0.0.1:9000/
        - name: GRAYLOG_PASSWORD_SECRET
          value: RAQFL8m4uOKfVGkgLfdLYGQcjjKvMKeX18TYaZ6pIsSpAQZA5c0Pjg6aoVF95PyE6jplblunu6gwMZH5IqfL9jrqipm3xaRD
        - name: GRAYLOG_ROOT_PASSWORD_SHA2
          value: e549ec65720451d8abfdcf094dba6ca34fe6e602e3c5225c73131234fb21b17a
        image: graylog/graylog:3.1
        name: gray
        ports:
        - containerPort: 9000
          protocol: TCP
        - containerPort: 1514
        - containerPort: 1514
          protocol: UDP
        - containerPort: 12201
        - containerPort: 12201
          protocol: UDP
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/graylog/data/config/graylog.conf
          name: gray-hostpath0
          subPath: graylog.conf
        volumeMounts:
        - mountPath: /usr/share/graylog/graylog.conf
          name: gray-hostpath1
          subPath: graylog.conf
        volumeMounts:
        - mountPath: /etc/graylog.conf
          name: gray-hostpath8
          subPath: graylog.conf
      volumes:
      - hostPath:
          path: /Users/mac/work/docker/conf/graylog
        name: gray-hostpath0
      - hostPath:
          path: /Users/mac/work/docker/conf/graylog
        name: gray-hostpath1
      - hostPath:
          path: /Users/mac/work/docker/conf/graylog
        name: gray-hostpath8
      restartPolicy: Always
status: {}
