apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: mongo
  name: mongo-deployment
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: mongo
    spec:
      containers:
      - image: mongo:3
        name: mongo
        #command:
            #- mongod
            #- "--bind_ip"
            #- 0.0.0.0
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /etc/mongod.conf
          name: mongo-hostpath
          subPath: mongod.conf
      volumes:
      - hostPath:
          path: /Users/mac/work/docker/conf/mongo
        name: mongo-hostpath
      restartPolicy: Always
status: {}
