apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: default
  labels:
    io.kompose.service: mongo
spec:
  selector:
    io.kompose.service: mongo
  type: NodePort
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017 
    protocol: TCP
